[weapon]
mon_thu = ["孤云寒林", "高塔孤王", "远海夷地"]
tue_fri = ["凛风奔狼", "雾海云间", "鸣神御灵"]
wed_sat = ["狮牙斗士", "漆黑陨铁", "今昔剧画"]

[talent]
mon_thu = ["自由", "繁荣","浮世"]
tue_fri = ["抗争", "勤劳", "风雅"]
wed_sat = ["诗文", "黄金", "天光"]
